### ISSUE TITLE
Duplicated measures do not show

### ISSUE THREAD

**Issue by wenihal** [otykier/TabularEditor#311] opened 2019-08-08 08:41 UTC
Sometimes when you duplicate a measure, new one do not show up. Steps to reproduce:

1. Duplicate any measure
2. Rename new measure in a way that name won't be unique. You will see red sign that you cannot give that name.
3. Enter name that is unique.
4. Duplicate another measure.
5. New measure will not show up in the interface.

Tabular Editor 2.8.4

**Comment by dmarkle** [comment] 2019-08-10 11:00
Check that you don't have a filter showing in your filter box.  I've noticed this a couple of times, and this is usually the cause.  That being said, the flow around filtering and searching could be better...

**Comment by otykier** [comment] 2019-10-16 02:00
Fixed in [2.8.6](https://github.com/otykier/TabularEditor/releases/tag/2.8.6).

**Closed by otykier** 2019-10-16 02:00 UTC
