### ISSUE TITLE
Have annotations always expanded

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#227] opened 2018-12-02 15:46 UTC
We are now heavily using annotations and it is a bit of extra friction that everytime we change object we have to reopen the annotation list. We would probably always want it to be expanded. Could TE remember whether we expanded or collapsed last (probably best) or provide an option for this?

**Comment by o-o00o-o** [comment] 2018-12-02 15:53
hmm it does seem to be doing this now.. not sure why I was feeling that it wasn't.. Ill monitor

**Comment by otykier** [comment] 2018-12-03 16:03
I was only able to reproduce this issue in cases where the script (temporarily) removes all annotations from the currently selected object in the explorer tree. Is this consistent with what you're seeing, or am I missing something?

**Comment by otykier** [comment] 2018-12-03 19:48
Yes, the property grid stores the expand/collapse state of all properties by their name. Since folders do not have an annotation property, and the default state for expandable properties is collapsed, that explains why you're seeing that. As a workaround, I suggest you click on the little arrow to the left of the folder icon, whenever you want to expand/collapse a folder, as this will not change the current selection in the grid (and thereby, the annotations collection in the property grid will stay in its current state).

I did locate a bug that causes the property grid to refresh every time annotations are modified within a script. This explains why the annotations collection collapses if a script temporarily removes all annotations from the currently selected object. It might also cause the script to run slowly if a lot of annotation changes are made to the currently selected object.

**Comment by otykier** [comment] 2019-01-23 14:13
Fixed in [2.8](https://github.com/otykier/TabularEditor/releases/tag/2.8)

**Closed by otykier** 2019-01-23 14:13 UTC
Labels: bug
