### ISSUE TITLE
Desktop shortcut created despite checkbox not checked during installation

### ISSUE THREAD

**Issue by DaniilMaslyuk** [otykier/TabularEditor#278] opened 2019-04-13 07:00 UTC
During the installation, I did not enable desktop shortcut creation, and it was created anyway. This has been happening for a few months now.

**Comment by otykier** [comment] 2019-04-24 12:44
Fixed in [2.8.2](https://github.com/otykier/TabularEditor/releases/tag/2.8.2). Thanks for reporting!

**Closed by otykier** 2019-04-24 12:44 UTC

**Comment by DaniilMaslyuk** [comment] 2019-05-11 02:25
Just installed 2.8.2 (updated from the previous version) -- still got a desktop shortcut :-(

**Comment by otykier** [comment] 2019-05-11 09:07
That’s weird. Could you try to do a clean install, and provide the exact steps/options you choose within the installer? Thanks!

**Comment by DaniilMaslyuk** [comment] 2019-05-11 10:41
I've recorded a GIF (under 20 seconds). Please let me know if there are any other details you'd find helpful. 
![Installation](https://user-images.githubusercontent.com/10683126/57568612-2edb8700-742d-11e9-9da0-74517660f401.gif)

**Comment by otykier** [comment] 2019-05-16 09:59
I'm not able to reproduce this behaviour on my end. Could you try with the newest [2.8.3](https://github.com/otykier/TabularEditor/releases/tag/2.8.3) installer, please?

**Comment by DaniilMaslyuk** [comment] 2019-05-16 11:50
It creates a shortcut, which disappears after some time, ha-ha. Happy with it as is, thank you!
