### ISSUE TITLE
Duplication of Measures when applying Formatting String to Calculation Item

### ISSUE THREAD

**Issue by wodraeve** [otykier/TabularEditor#855] opened 2021-05-25 23:00 UTC
When the formatting string against a calculation item is defined, upon committing the changes, existing measures are duplicated with visibility set to 'No'. Trying to remove these 'ghost'-measures results in error messages

1. Go to the calculation item
2. Click on format string. Enter the expression. This can be a static expression, this does not seem to affect the outcome
3. Commit the changes

Measures are duplicated

**Application specifics**
 - Tabular Editor version: 2.16.1
 - Power BI Desktop Version: 2.93.641.0 64-bit (May 2021)
 
Before:
![image](https://user-images.githubusercontent.com/22193657/119578718-e6703700-bd71-11eb-96f5-a460fde795de.png)

Making the change:
![image](https://user-images.githubusercontent.com/22193657/119578763-fb4cca80-bd71-11eb-8ee7-e6918f004c31.png)

After saving:
![image](https://user-images.githubusercontent.com/22193657/119578778-043d9c00-bd72-11eb-9665-f530b2cd6a9b.png)

Trying to delete:
![image](https://user-images.githubusercontent.com/22193657/119578809-10295e00-bd72-11eb-8bd5-1b137486c151.png)

```
Error Message:
---SAFE-MESSAGE---INamedMetadataObjectCollection<IMeasure> item not found

Stack Trace:
System.Collections.Generic.KeyNotFoundException
   at Microsoft.PowerBI.Client.Windows.Modeling.DataModelExtensions.ThrowIfNotFound[T](T foundItem, INamedMetadataObjectCollection`1 list, String name, String schemaName)
   at Microsoft.PowerBI.Client.Windows.Modeling.DataModelExtensions.GetExpected[T](INamedMetadataObjectCollection`1 list, String name, String schemaName)
   at Microsoft.PowerBI.Client.Windows.Modeling.DataModelExtensions.FindModelItem(IDataModel model, ObjectType objectType, String schemaName, String tableName, String itemName, String hierarchyLevelName, Boolean expected)
   at Microsoft.PowerBI.Client.Windows.Commands.ApplicationCommands.ObjectNameCommandParameter.ToDataModelItem(IDataModel dataModel)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.PowerBI.Client.Windows.Commands.ApplicationCommands.ModelingCommands.DeleteObjects(IWindowService windowService, IExceptionHandler exceptionHandler, IEnumerable`1 deleteObjectsParameters)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<HandleAwaitableAsyncExceptions>d__1.MoveNext()

Stack Trace Message:
---SAFE-MESSAGE---INamedMetadataObjectCollection<IMeasure> item not found

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace, String exceptionMessage)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.GetStackTraceInfo(Exception e)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.ReportException(IWindowHandle activeWindow, IUIHost uiHost, FeedbackPackageInfo feedbackPackageInfo, Exception e, Boolean useGDICapture)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.<>c__DisplayClass15_0.<HandleException>b__0()
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.HandleException(Exception e)
   at Microsoft.PowerBI.Client.Windows.Utilities.UIBlockingAwareExceptionHandler.HandleException(Exception e)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<HandleAwaitableAsyncExceptions>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.HandleAwaitableAsyncExceptions(IExceptionHandler exceptionHandler, Func`1 asyncFunc)
   at Microsoft.PowerBI.Client.Windows.Commands.CompositeCommand`1.Execute(ICommand command, Object parameter)
   at Microsoft.Practices.Prism.Commands.CompositeCommand.Execute(Object parameter)
   at Microsoft.PowerBI.Client.Windows.Commands.CompositeCommand`1.Execute(T parameter)
   at Microsoft.PowerBI.Client.Windows.CommandStoreHostService.<>c__DisplayClass13_0.<Execute>b__0()
   at Microsoft.PowerBI.Client.Windows.HostServiceDispatcher.<>c__DisplayClass7_0.<ExecuteOnUIThreadAsync>b__0(Object t)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass4_0.<Main>b__1()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<>c__DisplayClass3_0.<HandleExceptionsWithNestedTasks>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)


PowerBINonFatalError:
{"AppName":"PBIDesktop","AppVersion":"2.93.641.0","ModuleName":"Microsoft.PowerBI.Client.Windows.dll","Component":"Microsoft.PowerBI.Client.Windows.Modeling.DataModelExtensions","Error":"System.Collections.Generic.KeyNotFoundException","MethodDef":"ThrowIfNotFound","ErrorOffset":"195"}

Snapshot Trace Logs:
C:\Users\wdr\Microsoft\Power BI Desktop Store App\FrownSnapShotf0a840a4-778b-4901-8eb0-62f06f6428d4.zip

Model Default Mode:
Import

Model Version:
PowerBI_V3
```

**Comment by otykier** [comment] 2021-05-27 07:00
Duplicate of #831. In short: Not a Tabular Editor issue but a Power BI Desktop issue. Microsoft is aware and working on a fix.

**Closed by otykier** 2021-05-27 07:00 UTC
Labels: bug
