### ISSUE TITLE
Unable to deploy Model from Azure Pipeline

### ISSUE THREAD

**Issue by debashish10** [otykier/TabularEditor#606] opened 2020-09-11 05:54 UTC
**What are you trying to achieve?**

I am trying to deploy model from command line task from Azure pipeline  . I am using -S switch to invoke a script to update username , password for the data source . The pipelines were working since last one month but suddenly it stopped working with the error - Script execution error: Object reference not set to an instance of an object. Also this started happening once i updated Tabular editor version from 2.11.7 to 2.12.2 two days back .

Command line passed : TabularEditor.exe "C:\_work\r8\a/_CICD-Model Build/drop/CICD Model/Model.bim"  -S "C:\_work\r8\a/_CICD-Model Build/drop/SetConnectionStringFromEnv.cs" -Deploy "Provider=MSOLAP;Data Source=asazure://westeurope.asazure.windows.net/glbbirptaascicddev;User ID=***;Password=***" "CICD Model" -O -C -V -E

![image](https://user-images.githubusercontent.com/55327056/92868681-9f2e5a00-f41f-11ea-9d66-df6e3bbba489.png)

**What have you tried so far?**
I have also tried to run it directly from the agent pool machine via command line , i am getting same error from their as well . 
![image](https://user-images.githubusercontent.com/55327056/92870339-61323580-f421-11ea-9575-34dbee6bb294.png)

Has anything changed in the new release which is causing this or i am doing something wrong ?

**Comment by Mohit121288** [comment] 2020-09-11 06:29
I am also getting the same error. The pipeline works fine if I download the version 2.9.5 which I had before but when updating to 2.12.1, it fails with error 'Script execution error: Object reference not set to an instance of an object'. Please help mitigate this issue

**Comment by datacatsuk** [comment] 2020-09-11 07:51
I think is a duplicate of #604 
Same issue I see here.

**Comment by debashish10** [comment] 2020-09-11 07:58
Hi Daniel,

Please find the script content below :

var Con = Model.DataSources[0] as StructuredDataSource;                // Variable to store the first Connection

Con.Name =  Environment.GetEnvironmentVariable("Name"); // Update DataSource Display Name
Con.AuthenticationKind="UsernamePassword";
Con.Username = Environment.GetEnvironmentVariable("SQLUserName");     // Update the SQL Username
Con.Password = Environment.GetEnvironmentVariable("LOADER-PWD");     // Update the SQL Password from KeyVault
Con.Database=Environment.GetEnvironmentVariable("SQLDatabaseName");   // Update the SQL Database Name
Con.Server=Environment.GetEnvironmentVariable("SQLServerName");      // Update the SQL Username
Con.Credential["path"]=Environment.GetEnvironmentVariable("ServerPath");   // Updates connection

**Comment by otykier** [comment] 2020-09-11 08:12
Thanks. I located the bug and will provide a fix shortly.

**Comment by otykier** [comment] 2020-09-11 08:26
Duplicate of #604

**Closed by otykier** 2020-09-11 08:26 UTC
Labels: question

**Comment by otykier** [comment] 2020-09-11 08:32
Fixed in [2.12.3](https://github.com/otykier/TabularEditor/releases/latest)

**Comment by debashish10** [comment] 2020-09-11 08:36
Thanks a lot Daniel for the quick turnaround .
