### ISSUE TITLE
Detect and Notify to Reload a Model if underlying file changes

### ISSUE THREAD

**Issue by corycundy** [otykier/TabularEditor#450] opened 2020-04-24 19:22 UTC
Hi Daniel, we have recently incorporated the Tabular Editor into our multi-developer team. It would be very valuable if the Tabular Editor warned you with a dialog box when a file in the model folder changes (or the bim file if using a bim file) on the file system. Visual Studio has a similar warning and prompts you if you want to reload the bim file.

The scenario comes in if I have Tabular Editor open and I make some changes and save followed by merging my Dev branch down to my local feature branch. After bringing changes other developers have made and then inadvertently make another change (and save it) in Tabular Editor without re-opening it, I will overwrite any changes I just merged down and create a lot of local changes. 

 If Tabular Editor warned that a file in the underlying file system changed similar to how VS and SSMS do, I would almost always choose reload the model and be on my way.

I would think a File System Watcher could be used to implement this without too much trouble, but I'll leave that to you.

I didn't see this setting anywhere so I think this would be a great improvement.

Cory Cundy

**Comment by fmms** [comment] 2020-04-24 22:32
hi, thanks for reporting this. i guess this is a duplicate of #393 .

**Comment by corycundy** [comment] 2020-04-27 19:05
Yes, thank you. I didn't realize this, but it doesn't sound like the same feature.

Cory

**Comment by otykier** [comment] 2020-04-30 09:12
Closed as duplicate of #393

**Closed by otykier** 2020-04-30 09:12 UTC
