### ISSUE TITLE
This version of Tabular Editor requires the SQL AS AMO library version 15.0.0 (or newer).  

### ISSUE THREAD

**Issue by ArmanFalah** [otykier/TabularEditor#172] opened 2018-07-23 07:04 UTC
Hi Otykier,
Although I have installed the last version of SQL AS AMO on my server, the Tabular editor does not open!
I appreciate if you help me.
![image](https://user-images.githubusercontent.com/24508605/43061934-631c0f32-8e6c-11e8-945d-d6f664e68066.png)

Thanks, 
Arman

**Comment by otykier** [comment] 2018-07-23 07:33
Hi Arman,
Could you try to download and install the .msi version instead? That one includes the dll dependencies.
Best regards,
Daniel

**Comment by otykier** [comment] 2018-08-09 14:26
Closed as duplicate of #167

**Closed by otykier** 2018-08-09 14:26 UTC
Labels: bug
