### ISSUE TITLE
There was  was no response when connecting the dataset in the premium

### ISSUE THREAD

**Issue by jasonlaw997** [otykier/TabularEditor#678] opened 2020-11-12 12:35 UTC
I guess ,there are too much datasets in the workplace.
Trying to connect the the other one was ok.
![1](https://user-images.githubusercontent.com/37357651/98940878-a3ade680-2526-11eb-922c-69c5d0208786.png)

**Comment by otykier** [comment] 2020-11-12 14:42
Are you able to connect to the workspace using SSMS?

If you know the ID or name of the dataset you want to open, you may also launch Tabular Editor using the following command:

```shell
TabularEditor "<xmla endpoint>" "<dataset ID/name>"
```

For example, if I have a dataset named "DemoDataset" on my "DemoWS" workspace, I can connect directly to that using:

```shell
TabularEditor "powerbi://api.powerbi.com/v1.0/myorg/DemoWS" "DemoDataset"
```

**Comment by jasonlaw997** [comment] 2020-11-12 15:35
powerbi://api.powerbi.cn/v1.0/myorg/workplace;initial catalog=dataset1

Using this is command ,I can connect to daxstudio,but connecting to tabular editor will show all of datasets.
Using your command,it show the message "can not found the workplace“

**Comment by otykier** [comment] 2020-11-13 08:55
Could you try to include your user name in the connection string, when executing Tabular Editor from the command line:

```shell
TabularEditor "Provider=MSOLAP;Data Source=powerbi://api.powerbi.cn/v1.0/myorg/workspace;User ID=username@domain.com" "dataset"
```

**Comment by otykier** [comment] 2020-11-16 13:54
[Tabular Editor v. 2.13.0](https://github.com/otykier/TabularEditor/releases/latest) uses the latest TOM/AMO which should have better connectivity with Power BI Premium. Could you please try this version to see if it solves the issue?

**Comment by jasonlaw997** [comment] 2020-11-17 02:56
I try again ,but the  v. 2.13.0  did not solves the issue.

**Comment by jasonlaw997** [comment] 2020-12-04 06:07
It had shown the mmessages  when be waitting 15 min：
“**The session has been cancelled because the database it is connected to has been evicted to free memory for other operations**“
![错误信息](https://user-images.githubusercontent.com/37357651/101127995-af7a5d80-3639-11eb-872b-401911d36049.png)

**Comment by otykier** [comment] 2020-12-04 08:11
Thanks for the update. I think I know what the issue is: Tabular Editor is enumerating all the datasets in the workspace when populating the list of databases after you connect to the server. I think this is causing the Power BI service to load those dataset into memory, where as there would normally be many datasets in the evicted state. I will ask the team at Microsoft if there is any way to enumerate the datasets without causing them to be loaded into memory on the service.

Did you try the workaround with launching Tabular Editor from a command line?

**Comment by otykier** [comment] 2020-12-04 12:24
I believe this issue is now fixed. Could you please try the latest version of [Tabular Editor 2.13.2](https://github.com/otykier/TabularEditor/releases/latest), to see if this issue is resolved? Thanks!

**Comment by jasonlaw997** [comment] 2020-12-04 12:50
I try the latest version of Tabular Editor 2.13.2,and it works.A lot of thanks！
Now I can playing the premium with the tabular editor happily

**Comment by otykier** [comment] 2020-12-04 22:02
Good to hear it and thanks again for reporting the issue!

**Closed** 2020-12-07 08:04 UTC
Labels: bug
