### ISSUE TITLE
Power Query Data source

### ISSUE THREAD

**Issue by ArmanFalah** [otykier/TabularEditor#671] opened 2020-11-07 17:14 UTC
when you have a power query data source and you are using this data source to connect to a database when you deploy the model to an existing database, the connection of the deployed database doesn't have a password.

this only happens when you are deploying the model this does not happen when you connect directly to the model

it is interesting that when you uncheck the data source option it still affects the data source

**Comment by otykier** [comment] 2020-11-09 08:24
Closed as duplicate of #194. See also #596 and #645.

**Closed by otykier** 2020-11-09 08:24 UTC
Labels: bug
