### ISSUE TITLE
AlternativeOf.BaseTable property cannot be set in the Properties grid

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#794] opened 2021-03-09 11:32 UTC
**Describe the bug**

This code returns 'null' even with a valid AlternativeOf.BaseColumn
Model.Tables["TableName"].Columns["ColumnName"].AlternateOf.BaseTable.Output();

This code returns fine (as stated above)
Model.Tables["TableName"].Columns["ColumnName"].AlternateOf.BaseColumn.Output();

This code seems to be the only way to get the BaseTable
Model.Tables["TableName"].Columns["ColumnName"].AlternateOf.BaseColumn.Table.Output();

Also, the 'BaseTable' does not show in the properties window within the AlternateOf (well, only as the prefix for the BaseColumn). 

**Expected behavior**
The first script (BaseTable) should output the base table.

**Application specifics**
 - Tabular Editor version: 2.14.2

**Comment by otykier** [comment] 2021-03-09 11:39
From the [TOM docs](https://docs.microsoft.com/fr-fr/dotnet/api/microsoft.analysisservices.tabular.alternateof.basetable?view=analysisservices-dotnet):

> A reference ID to the referenced source table. You may either define BaseTable or BaseColumn, but not both.

So in other words, BaseTable is null by design when BaseColumn is assigned, but I don't know enough about aggregations to explain why this is so.

**Comment by otykier** [comment] 2021-03-09 12:39
Okay, after looking a little more into this I see that the behavior in the Properties Grid could be improved, so that the BaseTable property will be visible when Summarization is set to "Count", and the BaseColumn property is visible when Summarization is set to any other value.

But you should still be able to set the BaseTable property through a script for now.

**Comment by m-kovalsky** [comment] 2021-03-09 12:55
Got it. So devs would enter in the Summarization first as ‘Count’ and then specify the BaseTable.

But what if someone sets the Summarization to ‘Count’ and sets the base table and then wants to change it to use BaseColumn? It’s tricky because right now the BaseColumn shows the table name as well.

**Comment by otykier** [comment] 2021-03-19 13:59
Fixed in [2.15.0](https://github.com/otykier/TabularEditor/releases/tag/2.15.0).

In addition, you can now add/remove the AlternateOf object by clicking on the ellipsis-button or right-clicking in the Property Grid (no more scripting, yay!):

![image](https://user-images.githubusercontent.com/8976200/111791598-a7ca8600-88c3-11eb-9599-32fbe9355015.png)

**Closed by otykier** 2021-03-19 13:59 UTC
Labels: bug

**Comment by m-kovalsky** [comment] 2021-03-19 14:23
Amazing, thanks! One thing - when I click on the '...' within Alternate Of, it creates the alternate of. Instead of it automatically creating the Alternate Of, perhaps it gives the same 'Add Alternate Of' option. Same thing for removing Alternate Of (through the ...). Currently the '...' goes away after Alternate Of is added. I know you can right click to remove the alternate of but it's not exactly intuitive since I don't think any other properties are set through right clicking (within the properties window).
