### ISSUE TITLE
Creating new measure - error message: "Unexpected column name.."

### ISSUE THREAD

**Issue by svenseidor** [otykier/TabularEditor#321] opened 2019-09-10 07:00 UTC
![Tabular Editor Error Message 2019 09 09](https://user-images.githubusercontent.com/55108103/64590953-fdf26b00-d3a8-11e9-9681-978184bf9eb7.PNG)

Hi

Firstly, Daniel, I think you have created an amazing product.  I use it often and it is an incredible time-saver.  Sincerely, thank you for your hard work!  And for your generosity to share this for free.

I am, however, experiencing a bug which I would love some assistance to solve please.  I am trying to create new measures in TE for a PBIX file and I receive an error about an "Unexpected column name" and I don't understand what this means nor why it is coming up.  I can confirm I have tested this and I receive this on even the simplest of PBIX files (one table, two columns, two rows) and this occurs whether I create a new measure from scratch, or whether I duplicate an existing measure, or if I copy and paste an existing measure.

Thanks again for an amazing product, and I really hope you can help me solve this problem as it would allow me to use TE to create 30 measures in bulk as opposed to doing them one-by-one in PBI Desktop, and we know that that is very slow and time-consuming.

Cheers
Sven

**Comment by otykier** [comment] 2019-09-12 03:28
This is a duplicate of #287. Unfortunately, this can’t be solved within Tabular Editor. Please try to export a .pbit file and make your bulk changes on that, or try the code shown in #287.

**Closed** 2019-09-12 03:28 UTC
