### ISSUE TITLE
Unable to deploy Tabular model using CICD with Tabular editor when the -R and -M switch is added

### ISSUE THREAD

**Issue by DSwain1996** [otykier/TabularEditor#542] opened 2020-07-22 19:18 UTC
I am getting the attached error when trying to deploy the model using the -R and -M Switch .
I have added a member to the role using the Azure AD option .

Command used to deploy using command line task in DevOps : TabularEditor.exe "$(ModelFilePath)"  -S "$(SetConnectionStringFromEnv)" -Deploy "Provider=MSOLAP;Data Source=$(AASServerUrl);User ID=$(AASAdminUser);Password=$(AASAdminPassword)" "$(ModelName)" -C -P -R -V -E

**##[error]Deployment failed! The JSON DDL request failed with the following error: Failed to execute XMLA. Error returned: 'ID cannot be specified for Azure Analysis Services role member: '<pii>GSolapure@slb.com</pii>'.**

![image](https://user-images.githubusercontent.com/55327056/88218735-17796a00-cc7e-11ea-9d6f-392450a876b1.png)

**Comment by otykier** [comment] 2020-07-23 16:57
Duplicate of #457 and #403.

Your model metadata should not contain role members defined with MemberID's, which is sometimes the case when the members have been added through Visual Studio.

You can use [this script](https://github.com/otykier/TabularEditor/issues/403#issuecomment-615070546) to recreate all role members without the MemberID.

**Closed by otykier** 2020-07-23 16:57 UTC
