### ISSUE TITLE
Unicode Char display in editor is wrong format

### ISSUE THREAD

**Issue by applezorro** [otykier/TabularEditor#294] opened 2019-05-23 09:22 UTC
DAX editor can not display unicode char correctly. eg. Chinese word. like:

create a new measure

```
Sales = 

// Please copy this measure into editor to see  
// 这是一个度量值

1

// end
```

**Comment by otykier** [comment] 2019-05-23 10:37
Duplicate of #283

**Closed by otykier** 2019-05-23 10:37 UTC
