### ISSUE TITLE
Deployments fails after replacing calculated table

### ISSUE THREAD

**Issue by KoenVerbeeck** [otykier/TabularEditor#710] opened 2020-12-11 13:25 UTC
**Describe the bug**
I have a table in the model, and a calculated table with is just a copy of that original table. I removed the calculate table and renamed the original table to the name of the calc table. When I try to deploy the solution, I get the following error:

![image](https://user-images.githubusercontent.com/7213731/101908193-ff1dd380-3bbb-11eb-9b10-03eb218f1b83.png)

**To Reproduce**
1. I have a table called "Master Table" and a calculated table which is just a copy of this master table, called "My Dimension".
2. I rename "My Dimension" to "My Dimension TBD". I change all relationships referring to the calc table to the master table.
3. I rename "Master Table" to "My Dimension".
4. I delete "My Dimension TBD".
5. When I deploy, I get the error that the table cannot be found.

**Expected behavior**
Since the Tabular Editor uses a two-step process, the model should be deployed to the SSAS instance.

**Observed behavior**
Deployment fails with an error message.

**Application specifics**
 - Tabular Editor version: 2.12.4
 - Semantic Engine used: SSAS Tabular
 - Model Compatibility Level: 1500

**Additional context**
When I look at the generated script, I can see the two-step process. In the first _createorreplace_, I don't see the table "My Dimension". In the second step, the table is present.
To be clear, this is a "delete and rename" scenario, so two modifications at the same time.

**Comment by KoenVerbeeck** [comment] 2020-12-11 13:34
Ok, so now on to the weird stuff:
I took the script generated by Tabular Editor. Executed only the first step. Success. The calc table is deleted. Then I took the second step and executed that one. Also success, the table was recreated. The issue seems to occur only when both steps are present in the script?

**Comment by KoenVerbeeck** [comment] 2020-12-11 15:07
I repeated the same process on another pair of "dimension - calculated table" (I have a lot of those to remove, unfortunately). This time I get the following error:

![image](https://user-images.githubusercontent.com/7213731/101918412-9e959300-3bc9-11eb-83d2-16e8e42835e9.png)
This column is referenced in a measure in the fact table.
I ran again the code from the first step, and this deletes the calculated table (as expected). However, the error returned is actually a warning, since the measure from the fact table is now referencing a column that doesn't exist anymore. It seems Tabular Editor mistakes this as an error.

![image](https://user-images.githubusercontent.com/7213731/101919483-e8cb4400-3bca-11eb-8455-d3355c64f133.png)

**Comment by otykier** [comment] 2021-02-01 21:22
If I understand you correctly, there are two different issues here:

1. issue: Two-step `createOrReplace` TMSL process runs fine when the two steps are executed one by one, but errors out when the full script is executed (which version of Analysis Services are you using, btw.?) I reported this issue to the AS engine team some time ago. Haven't received an update on it since.
2. issue: Tabular Editor displays XMLA warnings as an error message, even though deployment succeeds.

Would it be possible for you to test issue 1 against Azure Analysis Services to see if the AS engine team has resolved the issue on their side, since this post was created?

**Comment by KoenVerbeeck** [comment] 2021-02-02 14:14
We're using SSAS 2019, compat level 1500.
Regarding issue 2, I'm not sure the deployment succeeds. When you execute the two-step TSML process by hand, the warning is returned in the XMLA query window after executing the first step. Then you can still execute the second step manually and it succeeds. In Tabular Editor however, you get an error, which contains the message from the warning.
I'll have to see if I can reproduce this.

**Comment by otykier** [comment] 2021-03-01 08:20
Closing this as duplicate of #527

**Closed by otykier** 2021-03-01 08:20 UTC
Labels: bug
