### ISSUE TITLE
How can I change the compatibility level ? 

### ISSUE THREAD

**Issue by sqlenders** [otykier/TabularEditor#401] opened 2020-03-05 09:06 UTC
How can I change from version 1400 to 1500 (upgrade) 
How can I change from version 1500 back to 1400 (downgrade) 

When downgrading you should check for features you can't use like calculation groups.
I think you might split it between upgrade and downgrade.

**Comment by otykier** [comment] 2020-03-05 09:19
Currently, Tabular Editor does not let you change the compatibility level of a model. Please use a text editor to open your Model.bim or Database.json file and manually change the CL. Note that deploying a database with changed compatibility level on top of an existing database is not supported by Analysis Services (you would have to delete the existing database first).

**Comment by sqlenders** [comment] 2020-03-05 12:18
I already did it using a text editor. BTW I had no problems deploying and upgrading from 1400 to 1500  from Visual Studio or using Invoke-ASCmd. We did a migration from Tabular 1400 on premise to Tabular 1400 Azure  to Tabular 1500 Azure .  No deleting was needed.

**Comment by otykier** [comment] 2020-05-28 08:18
Duplicate of #424

**Closed by otykier** 2020-05-28 08:18 UTC

**Comment by zenzeinet** [comment] 2020-06-18 22:00
Hey, maybe I can finally teach you something :)
You can update a model compatibility level (only upwards) on the fly using
xmla (without deploying)
Credit where it is due, just update the appropriate xmla values

https://www.thisintelligentlife.net/upgrading-ssas-tabular-2016-2017

Note that this is broken for 2017 to 2019 saas before cumulative Update 3

Best regards

**Comment by otykier** [comment] 2020-06-23 13:29
[Version 2.11.0](https://github.com/otykier/TabularEditor/releases/tag/2.11.0) now allows you to modify the compatibility level of a model directly. Please note that AS still not not let you execute a CreateOrUpdate TMSL script on a database with a modified compatibility level. So in order to do an in place upgrade:

1. Open your model from the existing database, File > Open > From DB... (Ctrl+Shift+O)
2. Set the Compatibility Level to the new value under Model properties > Database > Compatibility Level (note, only upgrades are allowed!)
3. Save the model back to the database, File > Save (Ctrl+S)
