### ISSUE TITLE
Expand tree after searching

### ISSUE THREAD

**Issue by o-o00o-o** [otykier/TabularEditor#176] opened 2018-08-17 08:57 UTC
Not sure if this changed in the last few versions but it is really RSI inducing that every time you search it results in a collapsed tree. Could we expand all after the search runs?

**Comment by otykier** [comment] 2018-08-17 12:31
A fix is in the works. Will keep you posted.

**Comment by otykier** [comment] 2018-08-17 12:32
Closed as duplicate of #156

**Closed by otykier** 2018-08-17 12:32 UTC
