### ISSUE TITLE
Cannot create Calculated Table (receive unhandled exception error)

### ISSUE THREAD

**Issue by hdegroot** [otykier/TabularEditor#579] opened 2020-08-21 23:15 UTC
I cannot create a new Calculated Table. I receive an unhandled exception error.  See screenshot.

![image](https://user-images.githubusercontent.com/3802567/90942093-1c3e5480-e3c9-11ea-8d3b-cd8cedb4a53c.png)

This used to work. Shoot, now I have to use Visual Studio again. I love Tabular Editor!

Thanks for looking into this!

---Hugo

Here are the details of the error:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at TabularEditor.FormMain.nodeTextBox5_ValueNeeded(Object sender, NodeControlValueEventArgs e)
   at Aga.Controls.Tree.NodeControls.BindableControl.OnValueNeeded(NodeControlValueEventArgs args)
   at Aga.Controls.Tree.NodeControls.BindableControl.GetValue(TreeNodeAdv node)
   at Aga.Controls.Tree.NodeControls.BaseTextControl.GetLabel(TreeNodeAdv node)
   at Aga.Controls.Tree.NodeControls.BaseTextControl.MeasureSize(TreeNodeAdv node, DrawContext context)
   at Aga.Controls.Tree.NodeControls.NodeControl.GetActualSize(TreeNodeAdv node, DrawContext context)
   at Aga.Controls.Tree.TreeViewAdv.<GetNodeControls>d__114.MoveNext()
   at Aga.Controls.Tree.TreeViewAdv.<GetNodeControls>d__113.MoveNext()
   at Aga.Controls.Tree.TreeViewAdv.DrawNode(TreeNodeAdv node, DrawContext context)
   at Aga.Controls.Tree.TreeViewAdv.DrawRow(PaintEventArgs e, DrawContext& context, Int32 row, Rectangle rowRect)
   at Aga.Controls.Tree.TreeViewAdv.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
TabularEditor
    Assembly Version: 2.11.7517.20764
    Win32 Version: 2.11.7517.20764
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
TOMWrapper
    Assembly Version: 2.11.7517.20763
    Win32 Version: 2.11.7517.20764
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.AnalysisServices.Core
    Assembly Version: 19.6.0.0
    Win32 Version: 15.1.48.22
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.Core.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.AnalysisServices.Tabular
    Assembly Version: 19.6.0.0
    Win32 Version: 15.1.48.22
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.Tabular.DLL
----------------------------------------
Microsoft.AnalysisServices.Tabular.Json
    Assembly Version: 19.6.0.0
    Win32 Version: 15.1.48.22
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/Microsoft.AnalysisServices.Tabular.Json.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 2.11.7517.20764
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
FastColoredTextBox
    Assembly Version: 2.16.24.0
    Win32 Version: 2.11.7517.20764
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
Crad.Windows.Forms.Actions
    Assembly Version: 1.3.0.0
    Win32 Version: 2.11.7517.20764
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
Antlr4.Runtime
    Assembly Version: 4.5.0.0
    Win32 Version: 2.11.7517.20764
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
dm3jwxum
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.2.0
    Win32 Version: 2.11.7517.20764
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.0.0
    Win32 Version: 2.11.7517.20764
    CodeBase: file:///C:/Program%20Files%20(x86)/Tabular%20Editor/TabularEditor.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by otykier** [comment] 2020-08-24 07:54
This is a bug in 2.11.7. Try to disable additional metadata columns (Ctrl+F1). A new release where this is fixed, will be available shortly.

**Comment by otykier** [comment] 2020-08-24 13:08
Duplicate of #576 - Fixed in [2.12.0](https://github.com/otykier/TabularEditor/releases/tag/2.12.0).

**Closed by otykier** 2020-08-24 13:08 UTC
Labels: bug

**Comment by hdegroot** [comment] 2020-08-24 19:49
Thanks, Daniel.
The fix resolved the issue!
Best,
---Hugo
