### ISSUE TITLE
Working with Tabluar Editor causes the creation of display folders "format string measures" within Power BI Desktop

### ISSUE THREAD

**Issue by mario-octosgt** [otykier/TabularEditor#607] opened 2020-09-12 00:18 UTC
I'm taking this bug report from the Power BI Issues site, not sure if it is a problem is within Power BI Desktop or Tabular Editor, but the problem presents itself when using the combination of both tools.

https://community.powerbi.com/t5/Issues/Working-with-tabluar-editor-cause-creation-of-display-folders/idc-p/1356549#M60640

> Hello, I worked with the new function "External Tools" / "Tabluar Editor" to create calculation groups within my model - following a blog post of SQLBI . Afterwards I have in EACH table containing DAX measures a hidden display folder called "Format String Measures", which I cannot control (neither from PBI desktop nor from Tabluar Editor). The real problem is a side effect, which is, that I'm loosing the control over the measure formatting in PBI Desktop (Menu "Measure tools" / "Format" field is greyed out).
> So what did I do wrong? How can I again format my measures in PBI Desktop?

**Comment by mario-octosgt** [comment] 2020-09-12 00:19
FYI I'm not the original poster of the Power BI Desktop issue report, but I'm experiencing the same issue.

**Comment by paul-rami** [comment] 2020-10-09 14:39
Same issue for me. Image below. The format cannot be modified for any measure in the model. Thanks for the great tool @otykier, first real bug for me after months of use.

![image](https://user-images.githubusercontent.com/68693228/95596542-ce031480-0a4d-11eb-9e7b-5f6909b546f1.png)

**Comment by otykier** [comment] 2020-11-16 12:36
Is this still an issue with the November release of Power BI Desktop?

**Comment by Rickmaurinus** [comment] 2020-12-02 07:58
> Is this still an issue with the November release of Power BI Desktop?

I'm noticing the same issue, also within the Power BI november release. Once a measure's formatting has been changed in tabular editor, it can not again be changed in Power BI. Is this intended behaviour?

**Comment by otykier** [comment] 2020-12-02 12:32
@Rickmaurinus are you talking about the display folders that appear? Please see Marco Russo's answer in [that thread](https://community.powerbi.com/t5/Issues/Working-with-tabluar-editor-cause-creation-of-display-folders/idc-p/1356549#M60640).

I'm closing this issue here, as in any case, setting the DisplayFolder property using any external tool should be a supported operation. In other words, this is an issue with Power BI Desktop handling of format strings assigned through external tools.

**Closed by otykier** 2020-12-02 12:32 UTC
Labels: bug

**Comment by Rickmaurinus** [comment] 2020-12-02 12:43
> @Rickmaurinus are you talking about the display folders that appear? Please see Marco Russo's answer in [that thread](https://community.powerbi.com/t5/Issues/Working-with-tabluar-editor-cause-creation-of-display-folders/idc-p/1356549#M60640).
> 
> I'm closing this issue here, as in any case, setting the DisplayFolder property using any external tool should be a supported operation. In other words, this is an issue with Power BI Desktop handling of format strings assigned through external tools.

Hey @otykier , 
I'm not referring to the Display folders. I'm referring to when a measure is formatted using tabular editor, it is saved to the model. Then when one goes back to the Power BI model, ANY other measure that was not formatted by tabular editor, can not be formatted anymore using the Power BI interface. Is this expected behaviour?

**Comment by otykier** [comment] 2020-12-02 22:11
Did you happen to add a calculation group to your model? This can cause ALL measures' data types to decay to "Variant" (you can check the data types of measures using Tabular Editor, see #566). Once a measure is of type "Variant", its formatting options in PBI Desktop will be very limited, because Desktop treats such a measure as text, which is a bug (in Desktop). To work around this, you can get rid of the Format annotation as shown in #566 or you can switch to the Diagram View in PBI Desktop, and change the format of the measure to something other than Text.

**Comment by Rickmaurinus** [comment] 2020-12-03 07:26
> Did you happen to add a calculation group to your model? This can cause ALL measures' data types to decay to "Variant" (you can check the data types of measures using Tabular Editor, see #566). Once a measure is of type "Variant", its formatting options in PBI Desktop will be very limited, because Desktop treats such a measure as text, which is a bug (in Desktop). To work around this, you can get rid of the Format annotation as shown in #566 or you can switch to the Diagram View in PBI Desktop, and change the format of the measure to something other than Text.

Yep. I do have the calculation groups. Thanks for clarifying. I will try your workaround.


With regards,
Rick de Groot
