### ISSUE TITLE
2.6 client for SQL 2017 doesn't work

### ISSUE THREAD

**Issue by jawa-the-hutt** [otykier/TabularEditor#96] opened 2017-10-09 01:18 UTC
I have downloaded TabularEditor.v2.6-CL1400.zip file.  When I run the unzipped exe, nothing happens, Client doesn't run as far as I can tell.  

I then installed 2.6 for SQL 2016 via the MSI package and it installed fine and was able to pull and push models correctly directly from SSAS.  Tried to open at 1400 level compatible model.dim and Tabular Editor didn't know what to do with some of the options in the underlying JSON and errored out.  

I tried downloading the source for the 1400 compatible client and compiling it.  After working through several issues to get it to compile, it appears to compile, but the resulting exe exhibits the same behavior as the exe from the zipped file in the releases page.  

So, wondering what I can do to help troubleshoot this further.  I'm running the very latest version of Windows 10 and believe I have all the latest SQL 2017 compatible tools installed in SSDT and Visual Studio to manage 1400 level compatible models as I'm doing just that today.

**Comment by otykier** [comment] 2017-10-09 04:21
It sounds like you're missing the 2017 AMO libs. Could you try to download and install them [from here](https://go.microsoft.com/fwlink/?linkid=829578), prior to running the 2017 build of Tabular Editor?

A new installer that should take care of this automatically will be provided soon.

**Comment by NielsSkytte** [comment] 2017-10-09 05:26
Had the same issue and after placing the right libraries together with the .exe file it worked fine with a level 1400 model.

**Comment by otykier** [comment] 2017-10-09 06:15
@NielsSkytte could you check the build number of the AMO .dll's that you used, to get it working?

**Comment by NielsSkytte** [comment] 2017-10-09 06:29
@otykier have it running with 14.1.0.432 (the ones you gave me on SQL Sat the other day where 14.1.0.430).

@jawa-the-hutt you should be able to find the dll's in: 
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\SSAS\LocalServer
or similar. You need:
![image](https://user-images.githubusercontent.com/32463103/31326932-c6841b7e-accb-11e7-88aa-944b47b4a23f.png)
copy them to the tabular editor folder and it should start.

**Comment by otykier** [comment] 2017-10-09 06:38
Thanks @NielsSkytte . There seems to be a compatibility issue with AMO build 14.0.800.x which is the official build provided by MS. I am looking into this.

**Comment by otykier** [comment] 2017-10-09 07:05
Ok, so it seems the issue is that AMO build 14.0.800.x does not include the Newtonsoft.Json namespace (or at least, it seems to have been renamed internally to Microsoft.AnalysisServices.Tabular.Json). This is in contrast to build 13.0.x.x and build 14.1.x.x where the Newtonsoft.Json is indeed available. It is quite puzzling, as build 14.0.800.x is the one officially available for download from Microsoft, although SQL Server 2017 seems to ship with build 14.1.x.x, which works fine for Tabular Editor as Niels describes above.

I will see if I can get some advice from the MS folks about which build should preferably be referenced in Tabular Editor. For now, I hope you can use the workaround provided by Niels.

**Comment by jawa-the-hutt** [comment] 2017-10-09 11:58
Ok, the workaround provided by @NielsSkytte was successful.  Exe opens correctly and I was able to successfully open a 1400 level model.bim file.

Thanks @otykier and @NielsSkytte.

I'll leave this open for now if you want to use it to track the issue with MS.

**Comment by otykier** [comment] 2017-10-10 18:02
A new build was just released, fixing the dependency issue. This build will work with either version (14.0 or 14.1) of the AMO libs, so hopefully we can avoid this confusion going forward.

As a side note, I decided to stop providing a separate build for SQL Server 2016 (v. 13.0 of the AMO), as users should use the updated (14.x) AMO's by now anyway, as it is backwards compatible with SQL Server 2016, and solves some other issues too.

Closing this issue, but feel free to reopen if you're still having issues with the dependencies.

**Closed by otykier** 2017-10-10 18:02 UTC
