### ISSUE TITLE
Save To Folder ->  Lineage Tag messes up version control

### ISSUE THREAD

**Issue by infused-kim** [otykier/TabularEditor#819] opened 2021-03-30 10:46 UTC
**Describe the bug**
Hi, I am not sure if this is a bug or feature request...

I am using the save to folder feature for version control with git. Unfortunately since the introduction of the lineageTag it has become nearly impossible.

The tag seems to be changing regularly. Perhaps when different users save the model? And the changed lineage tags show up in git as a change, making it very difficult distinguish between real changes and just lineage tag changes.

Is there a way to export the folder without the lineage tag?

**To Reproduce**
1. Save pbix to folder
2. Check it into git
3. Upload to PBI service
4. Download pbix from service
5. Save pbix to the folder again
6. Run the diff

**Expected behavior**
Lineage tag not included in the export.

**Observed behavior**
Lineage tag included and creating differences in the model

**Application specifics**
 - Tabular Editor version: 2.15.2
 - Semantic Engine used: Power Bi

**Comment by otykier** [comment] 2021-03-30 11:05
Thanks for reaching out. I was not aware that LineageTags are regenerates all the time by Desktop. Will make sure to add a setting that allows you to ignore LineageTags when serializing the metadata as a folder.

**Comment by marcosqlbi** [comment] 2021-03-30 12:36
This is quite strange and it could failed the entire purpose of lineageTag - should we ask to Microsoft whether this is a bug?
I agree that a setting in Tabular Editor is the best way to manage that, because I would not have expected such a behavior.

**Comment by otykier** [comment] 2021-03-30 14:12
Yes @marcosqlbi we should certainly ask them. In general I feel we’re missing a lot of details regarding the LineageTag and SourceLineageTag properties.

**Comment by Indrenet** [comment] 2021-03-30 15:40
I just noticed that model comparison in AML Toolkit is also not working because of lineageTag because all measures (also old measures) just got a lineageTag and are marked as having "Different Definitions".
I am comparing Power BI Desktop file (measures created with V2.15) to Dataset in Service (measures created with V2.14 or V2.13).

**Comment by infused-kim** [comment] 2021-03-31 07:24
Awesome, thanks for adding this fix/feature to the roadmap @otykier.

If you add an option to ignore the `lineageTag` in the exports, could you also add an option to ignore `annotations`? There are frequently random annotations that are not useful for version control and pollute the change history.

## Workaround
In the meantime to solve my problem I have created a python script that removes the `lineageTag` and `annotations` keys in exported JSON files.

You can find the script here:
https://gist.github.com/infused-kim/915c9131d39f9301444362f555318bc7

## ALM Toolkit
@Indrenet yes, I have noticed the same issue with ALM Toolkit and opened an issue here:
https://github.com/microsoft/Analysis-Services/issues/102

**Comment by Indrenet** [comment] 2021-03-31 08:25
@infused-kim I suspect, that added lineage tag is a feature of power bi. 
If I take power bi file created in February version and compare it with data in service (created with February or earlier version) then ALM toolkit doesn't identify any changes. If I open the same file in March version of power bi and save it, then comparison identifies changes because of added lineageTag.

**Comment by infused-kim** [comment] 2021-03-31 10:01
@Indrenet, yes, and I think that's expected behavior.

What's unexpected is that the lineageTags sometimes change. I have observed it when I uploaded a dataset to the service, then someone else downloaded it, edited and reuploaded it. Then I downloaded it and the lineageTags have changed.

**Comment by otykier** [comment] 2021-04-07 11:05
Update: Microsoft has confirmed this is a bug and are working on a fix ASAP. Thus, I will not provide the functionality mentioned earlier. If you have a requirement in the mean time, to get rid of the LineageTags before saving the model metadata, use the script I provided above.

**Comment by otykier** [comment] 2021-04-16 09:54
@infused-kim I received the below explanation from Microsoft. Could you confirm if the behaviour you're observing falls within one of these? Thanks!

The expected behaviors are shown below and in our repro, all results are as expected:
 
1.	If the report on PBI service already has LineageTags assigned, when different users download this report from service and open in desktop, desktop will not generate new LineageTags.
Local A and Local B should have the same LineageTag as what’s on the service.

![image](https://user-images.githubusercontent.com/8976200/115007435-4558ab80-9eaa-11eb-846b-e94f5606ef0e.png)

2.	If the report on PBI service has no LineageTags assigned, when different users download this report from service and open in desktop, desktop will generate new GUID as LineageTag for each object. 
So Local A and Local B who download the same report from service will end up having 2 reports with different LineageTags. And this is expected.
 
![image](https://user-images.githubusercontent.com/8976200/115007456-4be72300-9eaa-11eb-9b88-60dade951567.png)

3.	Base on scenario 2, when different users download the report on service that has no LineageTags, they all generated different LineageTags on their local, when User A upload the local report to service and replace the original report, 
The report on service will get updated with “TagA”. If later on User B also decides to upload his/her report to service, the report will again get updated with “TagB”. This is also expected.

![image](https://user-images.githubusercontent.com/8976200/115007490-51446d80-9eaa-11eb-8ae5-bb4e6bdbd7d0.png)

**Comment by otykier** [comment] 2021-04-21 20:32
So I guess the conclusion is that "it's not a bug, but a feature", and it depends on your specific workflow and the order in which you're publishing or downloading datasets to/from the PBI service.

Regardless, I decided to add an option that lets you ignore lineage tags, when serializing the model metadata as a file/folder:

![image](https://user-images.githubusercontent.com/8976200/115617233-73e2e600-a2f1-11eb-82ce-b0bd31b12236.png)

(Note, this is unchecked by default).

This is available in [2.16.0](https://github.com/otykier/TabularEditor/releases/tag/2.16.0).

**Closed by otykier** 2021-04-21 20:32 UTC
Labels: bug
