### ISSUE TITLE
Dataset is broken in Power BI after crating calculation groups

### ISSUE THREAD

**Issue by sunefibaek** [otykier/TabularEditor#628] opened 2020-09-28 08:54 UTC
When using Tabular Editor to create calculation groups in Power BI the measures in the dataset are seen as dimensions by PBI. I have found no way to recover the dataset afterwards. The measures are still not usable even after deleting the calculation groups. Any other datasets added to the model are also broken after this. Calculated measures do not seem to be affected by the issue. 

I am able to recreate the issue with datasets based on a HANA View and a CSV file. 

The calculation groups work fine when created, but only for calculated measures. 

**To Reproduce**
PBI Desktop:
Import CSV and create a visual to validate that the data is working as expected.
From external tools open tabular editor
Right click tables and create a calculation group
Click 'Save changes to the connected database
Return to PBI Desktop
All measures no behave as a dimension and no longer show the sum-sign left of them
(Bang head repeatedly on table in annoyance and be frustrated about working on your main report and not having a recent backup - this step is optional and not recommended)

**Expected behavior**
That the measures would still be a measure and not act as dimensions. 

**Observed behavior**
![image](https://user-images.githubusercontent.com/56259443/94411129-7e346b80-0178-11eb-9fcc-b6872a3937c2.png)
![image](https://user-images.githubusercontent.com/56259443/94411183-91473b80-0178-11eb-8db6-74126d370a5a.png)
![image](https://user-images.githubusercontent.com/56259443/94411359-c489ca80-0178-11eb-9267-a476ec5b89a4.png)
![image](https://user-images.githubusercontent.com/56259443/94411404-d23f5000-0178-11eb-9cdc-128f37a79c3f.png)

**Application specifics**
PBI Desktop, PBI Service
TE Version: 2.12.0
Dataset from HANA Calculation View and CSV

**Comment by otykier** [comment] 2020-09-28 10:25
Duplicate of #614

Please view the [documentation for calculation groups](https://docs.microsoft.com/en-us/analysis-services/tabular-models/calculation-groups?view=asallproducts-allversions#benefits).

Specifically, note that you have to enable **DiscourageImplicitMeasures**, before calculation groups can be added to a model. Tabular Editor does this for you automatically when adding the first calc group. When you later delete the calc groups from your model, you will have to manually set this property back to false.

**Closed by otykier** 2020-09-28 10:25 UTC
Labels: bug

**Comment by sunefibaek** [comment] 2020-09-28 11:41
Thank you for a very quick response! And sorry for missing the other issue report.

**Comment by otykier** [comment] 2020-09-28 11:59
> Hopefully there will be a way to handle this in the future

That won't happen. Calculation Groups, by design, cannot work with implicit measures, so in order to use them, the engine will likely always require the DiscourageImplicitMeasures flag to be set to true.

> just adds a ton of extra work having to create calculated key figs from already existing ones

For tabular modelling, it is a best practice to **always** create explicit measures. Why? Well, first of all, you run the risk of report creators using the wrong kind of aggregation (avg/min/max/sum), when using implicit measures. Secondly, if you have users that connect to your dataset using MDX-based client tools like Excel, Tableau, etc., they will not be able to query the model, since MDX requires the presence of explicit measures.

Luckily, with Tabular Editor, [there's a *very* easy way to create explicit measures from columns](https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets#create-measures-from-columns).

**Comment by sunefibaek** [comment] 2020-09-29 06:12
Hi
Great support! Thanks a lot - I think I'll experiment with reading the documentation...
