### ISSUE TITLE
Measure references invalidated in visuals when TabularEditor used to change measure names

### ISSUE THREAD

**Issue by MisterOttermayer** [otykier/TabularEditor#672] opened 2020-11-07 19:47 UTC
**Describe the bug**
I accessed Tabular Editor from within a Power BI desktop report by using the drop down menu for External Tools.
I renamed a number of measures in tabular editor (in bulk) and "Saved Changes to the connected database."
I ensured that the "Automatic formula fix-up" preference was checked.
Upon returning to my Power BI report, all references in visuals to the measures whose names were changed were invalidated.
It may be relevant that I had used the "Rename" option to change the name of the measures within the visuals. 

**To Reproduce**

**Expected behavior**
I expected my measure references to persist.

**Observed behavior**
A clear and concise description of what happened. Include any error messages or stack traces if possible. Also, feel free to add screenshots or recordings showing the problem.

**Application specifics**
 - Tabular Editor version: 2.12.1
 - Power BI Desktop
 - Model Compatibility Level: [e.g. 1400, 1500, 1520, etc.]

**Additional context**

**Comment by otykier** [comment] 2020-11-08 11:12
This is unfortunately by design. Tabular Editor can not access the visual tree of a pbix file, only the data model metadata. It is similar to when measures are renamed on an Analysis Services tabular model on which you have one or more reports in Live Connect mode.

**Comment by MisterOttermayer** [comment] 2020-11-08 16:56
Thank you for the reply. Is there an easy way to "un-invalidate" the measure references? I have a bunch of formatting applied to the columns that have become invalid, and it would be nice to preserve the formatting. But there is no obvious way to re-establish the link. Can I use maybe Dax Studio or some other tool to re-assign the field?

**Comment by otykier** [comment] 2020-11-08 20:50
Not to my knowledge. The only tool that lets you edit visuals and how measures are displayed and formatted in them, is Power BI Desktop itself. You may have better luck by reverting the changes you made in Tabular Editor, i.e. renaming the measures back to their original names. Then, your existing visuals should work again, keeping their existing formatting settings. Then, to actually rename the measures, without losing the visual references, go back to Power BI Desktop and rename them there.

**Comment by otykier** [comment] 2021-03-02 15:13
@MisterOttermayer did you have any further questions or may we close this?

**Comment by MisterOttermayer** [comment] 2021-03-02 15:15
You may close it. Sorry if that was my obligation. I got the answer I
needed.

*   Franklin Parlamis*
   495 Miller Avenue, Suite 301, Mill Valley, CA 94941 | (415) 477-9071


   If you have received this message in error, please notify the sender and
delete this e-mail and its attachments from your computer.
   The information contained in this communication is for informational
purposes, and it should not be regarded as an offer to sell or a
solicitation of an offer to invest in any investment fund.

**Closed** 2021-03-02 15:17 UTC
Labels: question, waiting for author
