### ISSUE TITLE
Error saving .pbit file - encoding/decoding of json

### ISSUE THREAD

**Issue by Simo-climb** [otykier/TabularEditor#263] opened 2019-03-07 01:22 UTC
Hi guys
Great tool and have been gaining so much more efficiency managing 150+ measures in a current Power Bi project Vs the tedious and laggy editing in Power Bi Desktop... just wasn't efficient at all in desktop !

First off I fully acknowledged the risks of file corruption. So when I encountered the following issue I was somewhat prepared and have recovered. All good. But thought it would be worth posting the issue.

While adding a series of new measures in a .pbit file that was converted from a .pbix, all was going smoothly for some time.
Then somewhere along the line after saving the pbit file and closing it was not able to be opened the next time.
It gives me the following error " Error loading model from disc - "this file is not a valid PBIX/PBIT file".
hmmm ...
On investigation of the file I was able to open the .pbit file in a text editor and found that it contained json of many things such as table/model definitions but of interest to me it included all of my new dax measures. The file size was 2000kb vs 700kb which was my clue to investigate.

for example it began with
{
"name": "dfe0355f-aac6-43df-928f-3f0a1b7af881",
"compatibilityLevel": 1465,
"createdTimestamp": "2019-02-26T12:02:07.81+11:00",
"lastUpdate": "2019-02-28T09:29:24.783333+11:00",
"lastSchemaUpdate": "2019-02-26T12:02:07.81+11:00",
"lastProcessed": "2019-02-28T08:57:34.016667+11:00",
"model": {
"culture": "en-US",
"modifiedTime": "2019-02-26T01:02:08.553333",
"structureModifiedTime": "2019-02-27T21:56:51.806667",
"dataSources": [

On comparison to the previous versions of the same .pbi file I saw that these were NOT directly editable in a text editor and appeared to be a compressed format and un-recognisable.

If I can provide any system setup details that might help debug let me know.

So long story short I was able to identify the new measures in the json objects in the "corrupted" .pbit file and transfer to a new working copy. So I'm 95% back on track and happy.

But some issues/questions are :

1. Is the json output created by some tabular editor setting ? I can't seem to find an option for this ?
2. It was very helpful in other ways as it turns out and has go me thinking about xslt or json driven code generation for parametric inputs....or just simple github code managment..... another conversation there.
3. is there a way to convert the json based .pbit back to a useable "encoded" format ? While I recovered the measures I did loose a few other pieces of work that I won't be able to recover easily manually. So it would be great to recover it still.

Noting other git issues posted here, I was saving the already open .pbit file as different versions along the way. But this appeared to work.
I may have put the PC to sleep in between the save event. Though can't be sure.

Many thanks in advance !

Simon

**Comment by Simo-climb** [comment] 2019-03-07 03:11
Follow up to above issue:

By pure chance I just found the culprit for the behaviour. 

The error occurs when the .pbit is open in tabular editor, then the "show/hide hidden objects" button is clicked, then the file is saved with the hidden objects still turned on.

I had the error occur again but remembered that viewing hidden objects was something I did.

Once saved and closed the file is still "corrupt" unless there is a way to revert the "show hidden objects" action out side of Tabular Editor 

Re-opening it in it's raw json format is still of interest though.

If you "fix" this behaviour I would suggest that an option to export the model, specifically the dax as a json output would be a good option. I would be keen to explore a process of git commits to the file to see if measure changes can be version controlled ? Have you any thoughts on this ?

Cheers

**Comment by otykier** [comment] 2019-03-07 07:13
Hi Simon,
Thanks for reporting this, I'll investigate. The idea is that the file should always save back into the encoded .pbit format, supported by Power BI. If you need to save the file as json, you would use the "Save as..." option and choose the ".bim" file type. However, please be aware, that there is currently no way to go from a .bim file to a .pbit file (as the .pbit file contains a lot more than just the json model metadata). So a better solution in that case, would be to use some kind of script to auto-generate the measures, and then version-control the script, instead of saving the .pbit as a .bim.

**Comment by otykier** [comment] 2019-03-07 07:32
I am unable to reproduce the issue in version 2.8.1 of Tabular Editor.

If you're using the latest version, could you please provide exact repro steps, as well as post the content of your Preferences.json file located under `%appdata%\..\Local\TabularEditor` BEFORE running TabularEditor.exe. In my case, I did:

1. Open a .pbit file (CTRL+O)
2. Toggling hidden objects from hidden to visible (CTRL+5)
3. Save the file (CTRL+S)

This worked fine, and the .pbit file could be subsequently loaded in Power BI Desktop.

Thanks in advance!

**Comment by Simo-climb** [comment] 2019-03-08 00:16
Hi mate

I wasn't using the latest version. Was using 2.8.6964.26585. But before I update I re-ran the test.

At first I couldn't reproduce it also. Using a more recent version of the same pbix, converting to pbit, opening in tabular editor, hiding, then resaving... it worked fine.

But I went back to the original file that I had issues with and doing the process repro'd the error.

Attached is the file in question as this mat help. Plus the preferences file as requested.

I will now update and see if it still happens... stay tuned.

Thanks for you info re: working process and pbit back chain limitations. I had already worked out that I could rename the miscoded .pbit file simply as database.json and import to tabular editor as a bim file. Similarly renaming as a .bim file also worked. I looked for a while to rebuild the pbit from the bim..... and thanks for your info I now see that limitation. All good tho. I'm fully recovered.

Thanks for providing decent documentation and support ! makes a big difference mate !

I took some time reading your doco's and learned a hell of a lot more and got a lot more exicited about managing TOM objects at scale much better. Thanks !

[PBIX - DIM Model UAT Release_28Feb0.2.zip](https://github.com/otykier/TabularEditor/files/2943877/PBIX.-.DIM.Model.UAT.Release_28Feb0.2.zip)

[Preferences_2.8.694.zip](https://github.com/otykier/TabularEditor/files/2943879/Preferences_2.8.694.zip)

**Comment by Simo-climb** [comment] 2019-03-08 00:21
Updated to 2.8.1

error still occurs.... but only using the above .pbit source file and resvaing after hide toggled. Can't yet repro it on another file.

thanks again

**Comment by otykier** [comment] 2019-03-08 07:33
Okay, so I'm not a 100% sure we're looking at the same bug. I was not able to trigger the behaviour you observed by toggling the show/hide hidden objects.

However, I noticed that when using the "File > Save As..." option on a .pbit file, even when saving as a new .pbit file, the icon on the "Save" button changes from

![image](https://user-images.githubusercontent.com/8976200/54014294-74a17800-417c-11e9-942c-5bcbe8c71fa2.png)

to

![image](https://user-images.githubusercontent.com/8976200/54014324-8be06580-417c-11e9-8254-295232b89307.png)

The first icon indicates that the file will be saved in the proper .pbit format, where as the latter icon indicates that it will be saved in the .bim format (JSON). So that's definitely a bug.

Are you sure you didn't use the "File > Save As..." option somewhere along the way, when reproducing the issue?

**Comment by otykier** [comment] 2019-04-24 12:52
Fixed in [2.8.2](https://github.com/otykier/TabularEditor/releases/tag/2.8.2). Let me know if you have any further issues.

**Closed by otykier** 2019-04-24 12:52 UTC
