### ISSUE TITLE
Additional features - intellisense

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#560] opened 2020-08-06 08:12 UTC
Is there a plan to incorporate intellisense for DAX into Tabular Editor? It would be quite valuable and would aid in the transition of folks from SSDT (and PBI Desktop) to Tabular Editor. Thanks!

**Comment by otykier** [comment] 2020-08-06 08:25
Duplicate of #550

**Closed by otykier** 2020-08-06 08:25 UTC

**Comment by m-kovalsky** [comment] 2020-08-06 08:45
Great, thanks!
