### ISSUE TITLE
C# script runs but cannot be saved as custom action

### ISSUE THREAD

**Issue by FrankFromGermany** [otykier/TabularEditor#724] opened 2021-01-01 21:19 UTC
I've download the C# script MetadataExport available here: https://github.com/m-kovalsky/Tabular/releases/
It works but cannot be saved as a model-based custom action:

---------------------------
Validation failed
---------------------------
Compile failed, custom action contains errors and cannot be saved.
---------------------------

**Comment by otykier** [comment] 2021-02-01 20:31
Closing this since #735 is the cause. Michael's script uses a local variable called "act" which conflicts with the custom actions infrastructure. This will be fixed in next release. In the mean time, rename any instances of "act" in the script to something else.

**Closed by otykier** 2021-02-01 20:31 UTC
Labels: question
