### ISSUE TITLE
Adding a reference to TOMwrapper.dll in Excel 2013

### ISSUE THREAD

**Issue by didierterrien** [otykier/TabularEditor#413] opened 2020-03-29 13:16 UTC
Hi Daniel,

Thank you for this incredible tool !

I'm trying to add a reference to TOMwrapper.dll in Excel 2013 but I get this error : 
Impossible to add a reference to the file 

Adding the reference into Visual studio community 2019 works

**Comment by otykier** [comment] 2020-03-29 21:33
Could you provide some more details on how you’re adding the file as a reference in Excel? I wasn’t even aware that it was possible to add .NET libs in Excel. Is it for VBA/macros?

**Comment by didierterrien** [comment] 2020-03-30 08:41
Hello Daniel, 


Yes it is inside VBA editor. In the Tools menu , I select References. Then I click on the third button to look for a dll. 


https://docs.microsoft.com/fr-fr/office/vba/language/reference/user-interface-help/can-t-add-a-reference-to-the-specified-file 


Is TOMwrapper.dll 32 or 64 bits ? 


Have a nice day 

----- Mail original -----

De: "Daniel Otykier" <notifications@github.com> 
À: "otykier/TabularEditor" <TabularEditor@noreply.github.com> 
Cc: "Didier Terrien" <didier.terrien@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Dimanche 29 Mars 2020 23:33:22 
Objet: Re: [otykier/TabularEditor] Adding a reference to TOMwrapper.dll in Excel 2013 (#413) 



Could you provide some more details on how you’re adding the file as a reference in Excel? I wasn’t even aware that it was possible to add .NET libs in Excel. Is it for VBA/macros?

**Comment by otykier** [comment] 2020-03-30 08:56
It's 32 bits, as is Tabular Editor.

But the problem is that the TOMWrapper.dll is a .NET library, which was not designed for COM interoperability, [which is a requirement in order to load the DLL in VBA](https://stackoverflow.com/a/19955042/1594867). It is not a trivial amount of work to redesign TOMWrapper in order to support this.

May I ask what it is you're trying to achieve with this integration?

Could you perhaps achieve the same thing by calling Tabular Editor's [CLI](https://github.com/otykier/TabularEditor/wiki/Command-line-Options) with suitable arguments from your macro? For example, you could use VBA to generate a C# script that would update measure descriptions and DAX expressions or whatever, and then use the CLI to execute that script against a model from your macro.

**Comment by didierterrien** [comment] 2020-03-30 11:49
Ok Daniel, that's clear.
My company is settled in 22 countries so we need to translate many reports into 5 languages minimum. On the other hand, I have a macro in Excel which translates automatically PowerPoint files. I begun to adapt this macro for Power BI objects and got already some results. 
At this point I wonder what is the best solution for communication with  the model :  

1. SSAS API - it will take probably a lot of time for me understand how to use it
2. Tabular editor through TOMwrapper - not compatible
3. Tabular editor through - export / import translations - objects ids are missing
4. Tabular editor through custom actions - I tried but I'm not skilled enough with this interpreter so I suppose it will take a lot of time
5. Tabular editor through CLI - same than above

May be you know more possibilities ?

If you want some demonstration, we can have a short Skype meeting so you will understand  the interrest to do it in Excel

**Comment by otykier** [comment] 2020-03-30 13:36
I see, thanks for clarifying.

Option 1: You would face the same issue as for option 2. There's no COM interoperability in any of the API's available for SSAS, as far as I know. Maybe you can use some legacy OLEDB stuff, but then you'd have to execute TMSL/XMLA commands against the model, which is probably going to be very cumbersome and difficult.

Option 3: What object ID's are you referring to? Are you aware that you can load the exported JSON files into [this tool](https://www.sqlbi.com/tools/ssas-tabular-translator/)?

Option 4 and 5: Feel free to ask specific questions on what you want the scripts/custom actions inside Tabular Editor to do, and I'll be happy to help. It's very easy to set a translated name through a script. For example, the following script assumes that you've already added a Danish culture to your model. When run, the script will set the translated names of all selected measures to `<original measure name> in Danish`. So if you selected a measure named `[Reseller Sales]`, its translated name would be `[Reseller Sales in Danish]`:

```csharp
foreach(var measure in Selected.Measures)
{
    measure.TranslatedNames["da-DK"] = measure.Name + " in Danish";
}
```

Here's an [introductory article to scripting in Tabular Editor](https://github.com/otykier/TabularEditor/wiki/Advanced-Scripting). Here's a collection of [useful sample scripts](https://github.com/otykier/TabularEditor/wiki/Useful-script-snippets).

To execute a script from the command line, simply run Tabular Editor this way:

```bash
TabularEditor.exe "OriginalModel.bim" -S "MyScript.cs" -B "NewModel.bim"
```

This will load a model from a file called "OriginalModel.bim", execute the script called "MyScript.cs" and save the resulting model into a file called "NewModel.bim". You can find [all CLI options here](https://github.com/otykier/TabularEditor/wiki/Command-line-Options).

Closing this, but feel free to post new issues if you have any specific questions.

**Closed by otykier** 2020-03-30 13:36 UTC

**Comment by didierterrien** [comment] 2020-03-30 15:31
Thank you for your reply which is perfectly clear

Yes I know about SSAS Tabular Translator but it doesn't seem to be supported any more and there is no automatic translation.

The Ids could be for example the column Id in the model so if the column is renamed in the model, I will not consider it is a new column.

The script functionality in Tabular editor is absolutely amazing. I will try to manage with it but I didn't find yet an object ID. If I still don't find, I will create a new issue.
