### ISSUE TITLE
Undo causes crash (after advanced scripting)

### ISSUE THREAD

**Issue by m-kovalsky** [otykier/TabularEditor#647] opened 2020-10-11 07:43 UTC
**Describe the bug**
Undoing a specific action causes Tabular Editor to crash.

**To Reproduce**
1. Run the following code in the Advanced Scripting window (the beginning of the master model script).

var version = "$perspective"; // To Do: Replace this with the name of your perspective

// Remove tables, measures, columns and hierarchies that are not part of the perspective:
foreach(var t in Model.Tables.ToList()) {
    if(!t.InPerspective[version]) t.Delete();
    else {
        foreach(var m in t.Measures.ToList()) if(!m.InPerspective[version]) m.Delete();   
        foreach(var c in t.Columns.ToList()) if(!c.InPerspective[version]) c.Delete();
        foreach(var h in t.Hierarchies.ToList()) if(!h.InPerspective[version]) h.Delete();
    }
}
2. Press Ctrl-Z (while selecting an object from the model)

**Expected behavior**
Previously, this did not cause an error and T.E. to crash

**Observed behavior**
This message comes up.
![image](https://user-images.githubusercontent.com/29556918/95673075-3b2dbb80-0bae-11eb-8554-b2971161bea5.png)

After pressing 'Continue', Tabular Editor freezes and crashes.

**Application specifics**
 - Tabular Editor version: 2.12.4

**Comment by otykier** [comment] 2020-10-13 20:28
Can't reproduce this. Can you send me the Model.bim file on which you experienced this, with a description of exactly which object has to be selected in the tree in order for the crash to occur? Thanks!

**Comment by otykier** [comment] 2020-11-16 13:57
Fixed in [2.13.0](https://github.com/otykier/TabularEditor/releases/latest)

**Closed by otykier** 2020-11-16 13:57 UTC
Labels: bug

**Comment by m-kovalsky** [comment] 2020-11-18 09:29
Confirmed this is now fixed. Thanks so much!
