### ISSUE TITLE
Error occured during deployment

### ISSUE THREAD

**Issue by Guavaq** [otykier/TabularEditor#389] opened 2020-02-05 01:02 UTC
Hi there

Great product as always.

When I am deploying to AAS I get the following error shown below. It does appear to still complete the deployment.

![image](https://user-images.githubusercontent.com/31457981/73801680-f4114e80-4806-11ea-8f0e-9e55e294578f.png)

**Comment by otykier** [comment] 2020-02-05 17:22
I'm not able to reproduce this behaviour. If possible, could you e-mail me the .bim file of the model that you are deploying? do (at) kapacity.dk

**Comment by TheDataViking** [comment] 2020-02-05 22:53
@Guavaq I noticed the same error today as part of our release pipelines to Azure Analysis Services. I solved it by updating to the latest version of Tabular and AMO available in the portable version.

**Comment by otykier** [comment] 2020-02-06 09:12
Seems like Azure Analysis Services has been updated with a build not supported by the current AMO used by Tabular Editor (18.2.3).

I will provide an updated build that targets 18.4.0.5 shortly.

**Comment by Guavaq** [comment] 2020-02-06 09:14
Thanks @otykier it still deploys the measures. Just gives the error

**Comment by TheDataViking** [comment] 2020-02-06 09:17
Great @otykier 

It seems to even deploy the model fully for a new database. It just keep throwing the error

**Comment by otykier** [comment] 2020-02-06 12:12
Fixed in [2.9.2](https://github.com/otykier/TabularEditor/releases/tag/2.9.2).

**Closed by otykier** 2020-02-06 12:12 UTC

**Comment by Guavaq** [comment] 2020-02-06 21:40
Thanks @otykier  I can confirm it is now working!
