### ISSUE TITLE
Failed to update Power BI File

### ISSUE THREAD

**Issue by bolenik** [otykier/TabularEditor#381] opened 2020-01-10 23:31 UTC
Hi, 

i have an issue with updating Power BI File from Tabular Editor. 
I can open the file, change measures, but when I want to save it, i get an error below. 

Please advise me what to do. 

Regards, 
Borut

---------------------------
Could not save metadata changes to database
---------------------------
Failed to save modifications to the server. Error returned: 'Nepričakovano ime stolpca: stolpec »ObjectID.Expression« je bil prejet v naboru vrstic »ObjectTranslations«. Pričakovan je bil stolpec »ObjectID.Set«.

'.

Save the model as a file to make sure you do not lose any work. In case the database connection was lost, you can still apply your changes to the database by using the "Model > Deploy" option.
---------------------------
V redu   
---------------------------

**Comment by otykier** [comment] 2020-01-14 10:27
Duplicate of https://github.com/otykier/TabularEditor/issues/287

**Closed by otykier** 2020-01-14 10:27 UTC
