### ISSUE TITLE
Duplicating PowerBI Measure wont save

### ISSUE THREAD

**Issue by eugeneniemand** [otykier/TabularEditor#337] opened 2019-10-03 11:03 UTC
I have a PowerBI file, when I duplicate a measure inside or outside of display folders and click save I get the below error

![Could not save metadata changes to database](https://user-images.githubusercontent.com/6813309/66121716-bccf2e80-e5d5-11e9-94a7-8314c80e937d.png)

However, if I create the new Measure in TabularEditor it saves just fine

**Comment by otykier** [comment] 2019-10-09 07:20
This is a known limitation of Power BI currently (one of the reasons for the warning when you connect to an instance of Power BI).

Some users were able to work around this, by deleting all annotations and extended properties on the duplicated measures, before saving. Alternatively, save the .bpix file as a Power BI Template (.pbit), then load the pbit file directly in Tabular Editor and make the changes to that.

Closed as a duplicate of #287

**Closed by otykier** 2019-10-09 07:20 UTC
