### ISSUE TITLE
Error: Microsoft Analysis Mangement Objects required

### ISSUE THREAD

**Issue by q0-0n** [otykier/TabularEditor#146] opened 2018-04-16 13:01 UTC
When installing Tabular Editor a prompt windows pops up notifying me of the requirement of Microsoft Analysis Management Objects (v. 14.0 or newer) with a link to the Microsoft page. 

But, I have Microsoft Analysis Management Object 15.0.300.129 already installed.

Clicking "No" results in a termination of the installation.

What is the problem here?

![image](https://user-images.githubusercontent.com/18561774/38810415-fc42bda6-4186-11e8-9695-e06251ecd7e7.png)

**Comment by sdjdk** [comment] 2018-04-16 14:12
I have the exact same issue - I need Tabular Editor (and thank you for an awesome app) on a server where I can't download any software, so I downloaded and installed Analysis Management Objects 15.0.300.129 manually, but the installer doesn't recognize that I already have it installed.

**Comment by dmgdotnet** [comment] 2018-04-16 14:35
I think this is the same issue others have reported: https://github.com/otykier/TabularEditor/issues/144

If you use the ZIP and run the file directly it should work.

**Comment by otykier** [comment] 2018-04-17 09:49
Closed as duplicate of #131 - updated installer will be published later today.

**Closed by otykier** 2018-04-17 09:49 UTC

**Comment by q0-0n** [comment] 2018-04-23 07:47
Thank you for fixing the issue and notifying @otykier. Your app is awesome!
