### ISSUE TITLE
DAX intelliSense is one of the nicest feature is missing in Tabular editor. is it possible to get them added

### ISSUE THREAD

**Issue by tribhuwann** [otykier/TabularEditor#550] opened 2020-07-23 17:48 UTC

**Comment by otykier** [comment] 2020-07-24 13:46
Duplicate of #64

**Closed by otykier** 2020-07-24 13:46 UTC

**Comment by otykier** [comment] 2020-07-24 14:01
It’s in the works but I can’t provide an ETA at this time.

**Comment by tribhuwann** [comment] 2020-07-24 20:56
Hi Daniel,

Thanks for quick response and great to hear that it is in the works.
