### ISSUE TITLE
Copying Measures in Tabular Editor Doesnt Rename in PBI

### ISSUE THREAD

**Issue by MarkTimson-BIDev** [otykier/TabularEditor#546] opened 2020-07-23 11:16 UTC
Hi When Copying a measure using the "External Tools" feature in Power BI into Tabular Editor. Measure look like they have the right name in the Tabular Editor, When commiting back to Power BI They have the original Copied Name in the Tabular Editor Tool. See below: 

![image](https://user-images.githubusercontent.com/67047591/88280679-255ed780-ccde-11ea-98ae-4a9acb9d1bd6.png)

The Power BI Model Looks to have the right name but this is not reflected in the Table Def: 

![image](https://user-images.githubusercontent.com/67047591/88280765-55a67600-ccde-11ea-9b6a-c228df8da41e.png)

**Comment by otykier** [comment] 2020-07-23 12:19
Duplicate of #533

**Closed by otykier** 2020-07-23 12:19 UTC
