### ISSUE TITLE
More information, when opening erroneous model

### ISSUE THREAD

**Issue by lhammer1000** [otykier/TabularEditor#327] opened 2019-09-17 06:16 UTC
When opening a model that has some kind of error, I get a message like this:
![TabularEditorErrorOpeningModelFromDisk](https://user-images.githubusercontent.com/40360777/65015883-23d8bc00-d923-11e9-9039-3137f311d208.png)
In this case, I'm opening a model from folder.
Is would be really nice to get some information about what file the error is in and if possible, some indication about what object was erroneous or maybe the line number.

**Comment by lhammer1000** [comment] 2019-09-17 06:17
Also, when saving a model with errors, it would be neat to get more information about which object has errors.

**Comment by otykier** [comment] 2019-09-17 17:32
I will look into, whether Tabular Editor can provide information about which file contains invalid JSON (which is the cause of this error message).

Regarding your second question, Tabular Editor will never save invalid JSON to the file system. It is possible that your model contains semantic errors (for example, invalid DAX), but you should always be able to load a model that was saved from Tabular Editor, provided the individual files have not been changed in the meantime. If you're using source control such as Git, it is likely that some conflict markers have been added to the files (for example during a merge operation), which would make the JSON invalid, and this could cause an error like the one you are seeing.

**Comment by otykier** [comment] 2019-10-16 02:00
Fixed in [2.8.6](https://github.com/otykier/TabularEditor/releases/tag/2.8.6).

**Closed by otykier** 2019-10-16 02:00 UTC
