### ISSUE TITLE
Allow multi-select of objects in different display folders

### ISSUE THREAD

**Issue by KavasiMihaly** [otykier/TabularEditor#432] opened 2020-04-06 10:02 UTC
It seems that I cannot select items (measures) from separate folders even if they are in the same table.
Can this capability be added?
Thanks.

Really great tool

Version 2.9.7

**Comment by otykier** [comment] 2020-04-06 10:10
Correct - consider toggling off display folders if you need to select measures from different folders at once. The reason it’s not possible at the moment is that I had some issues with handling situations where you could theoretically drag a folder of objects inside itself, so the easiest option was to disallow selecting objects belonging to different parents in the tree. Will consider changing this behavior later on.

**Comment by otykier** [comment] 2020-06-20 18:45
Closing this as duplicate of the more general #489

**Closed by otykier** 2020-06-20 18:45 UTC
Labels: enhancement
