### ISSUE TITLE
When duplicating measures or undoing some batch operation the list of measures does not update

### ISSUE THREAD

**Issue by leniel** [otykier/TabularEditor#320] opened 2019-09-06 20:01 UTC
The workaround is clicking the Show/hide metadata information icon or even trying Toggle alphabetical order. This refreshes the measure list.

**Comment by otykier** [comment] 2019-10-16 00:48
Unable to reproduce as of 2.8.5. Please provide more information.

**Comment by otykier** [comment] 2019-10-16 02:00
Fixed in [2.8.6](https://github.com/otykier/TabularEditor/releases/tag/2.8.6).

**Closed by otykier** 2019-10-16 02:00 UTC
